### ISSUE TITLE
ERROR: An error occurred while sending get-request to http://cert.int-x3.letsencrypt.org/ (Status 301)

### ISSUE THREAD

**Issue by jtenniswood** [csmith/docker-letsencrypt-lexicon#3]
I'm getting this error and all the certificates are now invalid.
Hope it's a simple fix.
Thanks
 
```

+ Challenge is valid!
 + Requesting certificate...
 + Checking certificate...
 + Done!
 + Creating fullchain.pem...
  + ERROR: An error occurred while sending get-request to http://cert.int-x3.letsencrypt.org/ (Status 301)

Details:
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by ShaneMcC** [comment]
Seems like:

https://community.letsencrypt.org/t/dehydrated-caused-rate-limits-to-be-reached/52477
and
https://github.com/lukas2511/dehydrated/commit/7a0e71c6c2ccc6e98abca5ea1c7de28053e90c02

May be related.

0.6.0 of dehydrated includes that commit.

**Comment by jtenniswood** [comment]
Yes, sorry. I flushed to image and it fixed the issue.
Thanks for the quick reply
