### ISSUE TITLE
Certificate doesn't seems full

### ISSUE THREAD

**Issue by TwanoO67** [csmith/docker-letsencrypt-lexicon#4]
Hello,

I'm trying to get my certificates using your docker image.

I put my lexicon account, and my domains.txt seems to be taken.

When starting the container, some directory are created.
( archive, certs, accounts )
So it looks like my parameters are well passed to the container.

But inside certs, I found a directory name with my domain.
And inside that some files a generated :
```
-rw------- 1 root root  538 Oct 11 10:24 cert-1539246254.csr
-rw------- 1 root root    0 Oct 11 10:24 cert-1539246254.pem
-rw------- 1 root root  359 Oct 11 10:24 privkey-1539246254.pem
```

But the cert-*.pem is empty.

When i'm using certbot with the manual generation of my certificate, here's what I obtain:
```
-rw-r--r-- 1 root root 2179 Oct 10 17:19 cert1.pem
-rw-r--r-- 1 root root 1647 Oct 10 17:19 chain1.pem
-rw-r--r-- 1 root root 3826 Oct 10 17:19 fullchain1.pem
-rw-r--r-- 1 root root 1708 Oct 10 17:19 privkey1.pem
```

So with certbot the files are much bigger (and I have 4 of them), wherease with your docker, I get 3 files, and one of them is empty.

So I suppose that the certs generation as failed, but how can I get sure of that ?
Is there any log of action somewhere ?

**Comment by csmith** [comment]
Hello!

All the logs will be captured by docker, so you should just be able to do `docker logs containerName` (you can use `docker ps` to find the container name if you don't know it)

I wouldn't worry too much about the files being smaller - by default this will use an eliptic curve algorithm for the certs which does result in smaller file sizes than certbot's default which is RSA. Obviously there's something wrong with the zero byte one, though!

**Comment by TwanoO67** [comment]
Thanks for your fast answer :)

So in logs, I have this error:

```
  + ERROR: An error occurred while sending post-request to https://acme-staging.api.letsencrypt.org/acme/new-authz (Status 400)

Details:
{
  "type": "urn:acme:error:malformed",
  "detail": "Error creating new authz :: Wildcard names not supported",
  "status": 400
}
```

This seems odd as in certbot I can validate my wildcard domain without problems.
Any idea on how I could achieve that ?

At the moment, I tried:
-  *.mydomain.com in my domains.txt
which failed with the previous error.

- And directly mydomain.com
wich failed with the error
```
 + Generating private key...
 + Generating signing request...
 + Requesting challenge for mydomain.com...
deploy_challenge called: mydomain.com, zR56Mso4TXOI994jpSZi5mbR_f_56AJaE, ryDAVKf_0MHeoNVjjf-nXtI2CDYjmM9w
Arguments: Namespace(action='create', auth_application_key=None, auth_application_secret=None, auth_consumer_key=None, auth_entrypoint=None, content='rILKf_S7iZ0MHeoNVjjf-MiIknXtIYjmM9w', delegated=None, domain=mydomain.com', identifier=None, name='_acme-challenge.mydomain.com', priority=None, provider_name='ovh', ttl=None, type='TXT')
...
 File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 305, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.5/dist-packages/requests/models.py", line 379, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL 'None/auth/time': No schema supplied. Perhaps you meant http://None/auth/time?
```

It seems to me that the "None" in arguments could be the problem.
maybe it's coming from my docker env config.
But I tried with:
```
- LEXICON_OVH_ENTRYPOINT='ovh-eu'
- LEXICON_OVH_APPLICATION_KEY="zES...58M"
- LEXICON_OVH_APPLICATION_SECRET="dIht....m1"
- LEXICON_OVH_CONSUMER_KEY="r8zR98....VTN8fbceK"
```

and also:
```
- AUTH_ENTRYPOINT="ovh-eu"
- AUTH_APPLICATION_KEY="zESr....58M"
- AUTH_APPLICATION_SECRET="dIhtC....Sm1"
- AUTH_CONSUMER_KEY="r8zR....bceK"
``

both got the same result.
Any idea ?

**Comment by csmith** [comment]
Ah, yes, wildcard support probably needs me to do some updating to enable it. I've opened #5 to track that.

For the second error, the LEXICON_OVH_* keys are right, but I think the problem is how you're quoting them. For most of them you should be able to drop the quotes entirely:

```
- LEXICON_OVH_ENTRYPOINT=ovh-eu
```

If they've got some special chars in that the YAML parser doesn't like you can quote the whole thing:

```
- "LEXICON_OVH_...=...."
```

I think what's happening is Lexicon's OVH provider is getting an entrypoint value of `'ovh-eu'` (with the quotes), and failing to match it to just `ovh-eu`.
